#!/usr/bin/env bash
#
# Idempotent fixture bootstrap for CI (and local repro). Fetches:
#   - a pinned vpxtool release binary into build/vpxtool/
#   - a pinned vpinball checkout (sparse: scripts/ + src/assets/) into
#     build/vpinball-src/, used for VPINBALL_DIR (core.vbs etc.) and
#     as the source of the example .vpx files
# Then extracts the .vpx fixtures into tables/<name>/ and writes
# examples/vpx_config.vbs pointing at the in-repo paths.
#
# Override pins via environment:
#   VPINBALL_REV=<sha>
#   VPXTOOL_VERSION=v0.30.0
#
set -euo pipefail

VPINBALL_REPO="${VPINBALL_REPO:-https://github.com/vpinball/vpinball.git}"
VPINBALL_REV="${VPINBALL_REV:-5b7c795e0689fdf85ccc55e291c417a86bacd324}"
VPXTOOL_VERSION="${VPXTOOL_VERSION:-v0.30.0}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BUILD_DIR="$REPO_ROOT/build"
VPINBALL_SRC="$BUILD_DIR/vpinball-src"
VPXTOOL_DIR="$BUILD_DIR/vpxtool"
VPXTOOL_BIN="$VPXTOOL_DIR/vpxtool"

# Per-fixture: <name in tables/>:<filename in vpinball src/assets>
FIXTURES=(
    "example_table:exampleTable.vpx"
    "light_seq_table:lightSeqTable.vpx"
)

mkdir -p "$BUILD_DIR"

# 1. Fetch vpxtool release binary.
if [[ ! -x "$VPXTOOL_BIN" ]]; then
    echo "==> Downloading vpxtool $VPXTOOL_VERSION"
    arch="$(uname -m)"
    case "$arch" in
        x86_64)  arch_tag="x86_64" ;;
        aarch64) arch_tag="aarch64" ;;
        *) echo "unsupported arch: $arch" >&2; exit 1 ;;
    esac
    url="https://github.com/francisdb/vpxtool/releases/download/${VPXTOOL_VERSION}/vpxtool-linux-${arch_tag}-${VPXTOOL_VERSION}.tar.gz"
    mkdir -p "$VPXTOOL_DIR"
    curl -fsSL "$url" | tar -xz -C "$VPXTOOL_DIR"
    chmod +x "$VPXTOOL_BIN"
else
    echo "==> Reusing $VPXTOOL_BIN"
fi

# 2. Fetch vpinball at pinned rev. Sparse-checkout so we only pull
#    scripts/ (core.vbs et al, used as VPINBALL_DIR by the framework)
#    and src/assets/ (the .vpx fixtures), not the full ~1 GB tree.
if [[ ! -d "$VPINBALL_SRC/.git" ]]; then
    echo "==> Cloning vpinball $VPINBALL_REV (sparse)"
    mkdir -p "$VPINBALL_SRC"
    git -C "$VPINBALL_SRC" init -q
    git -C "$VPINBALL_SRC" remote add origin "$VPINBALL_REPO"
    git -C "$VPINBALL_SRC" config core.sparseCheckout true
    cat > "$VPINBALL_SRC/.git/info/sparse-checkout" <<'EOF'
scripts/
src/assets/
EOF
    git -C "$VPINBALL_SRC" fetch --depth=1 origin "$VPINBALL_REV"
    git -C "$VPINBALL_SRC" checkout -q FETCH_HEAD
else
    current="$(git -C "$VPINBALL_SRC" rev-parse HEAD 2>/dev/null || echo none)"
    if [[ "$current" != "$VPINBALL_REV" ]]; then
        echo "==> Refreshing vpinball to $VPINBALL_REV"
        git -C "$VPINBALL_SRC" fetch --depth=1 origin "$VPINBALL_REV"
        git -C "$VPINBALL_SRC" checkout -q FETCH_HEAD
    else
        echo "==> Reusing vpinball src at $VPINBALL_REV"
    fi
fi

# 3. Extract each fixture under tables/<name>/.
for entry in "${FIXTURES[@]}"; do
    name="${entry%%:*}"
    vpx="${entry##*:}"
    src="$VPINBALL_SRC/src/assets/$vpx"
    dest_dir="$REPO_ROOT/tables/$name"
    if [[ ! -f "$src" ]]; then
        echo "error: $src missing in vpinball checkout" >&2
        exit 1
    fi
    mkdir -p "$dest_dir"
    cp "$src" "$dest_dir/"
    echo "==> Extracting $name <- $vpx"
    "$VPXTOOL_BIN" extract "$dest_dir/$vpx" -f >/dev/null
done

# 4. Generate examples/vpx_config.vbs pointing at in-repo paths. Native
#    Linux paths (per the framework's libwinevbs-friendly convention).
cat > "$REPO_ROOT/examples/vpx_config.vbs" <<EOF
' Auto-generated by scripts/ci-fetch-fixtures.sh -- do not edit.
Option Explicit
Dim VPINBALL_DIR : VPINBALL_DIR = "$VPINBALL_SRC"
Dim TABLES_DIR   : TABLES_DIR   = "$REPO_ROOT/tables"
EOF

echo "==> Fixtures ready"
echo "    VPINBALL_DIR=$VPINBALL_SRC"
echo "    TABLES_DIR=$REPO_ROOT/tables"
for entry in "${FIXTURES[@]}"; do
    name="${entry%%:*}"
    echo "    tables/$name/"
done
